repos:
- repo: https://github.com/doublify/pre-commit-rust
  rev: master
  hooks:
    - id: fmt
    - id: clippy
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: master
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.9
  hooks:
    - id: remove-crlf
    - id: remove-tabs
